### PR TITLE
Upgrade sqlite to 3.15, enable FTS4, FTS5

### PR DESCRIPTION
**Pull request by wmertens**
3.15 has row values, which allow pagination without using offset, and there have been a bunch of fixes since 3.9.

Builds fine on OS X 10.11.6.

FTS4 and FTS5 only add a few 100KB to the binary size.

### CODE REVIEW

**Comment by rnewman** [comment]
3.15 also allows the use of deterministic functions in partial index expressions, which is _huge_.

**Comment by springmeyer** [comment]
Thank you @wmertens, merging now. This will be part of the upcoming `v3.1.7` release.

**Comment by osi-oswald** [comment]
When I call `SELECT sqlite_version()` I get `3.13.0`, shouldn't it be `3.15.0` according to this PR?

**Comment by wmertens** [comment]
I get this:

$ node -e 'var d = new (require("sqlite3").Database)(":memory:", function()
{d.all("select sqlite_version()", console.log)})'

null [ { 'sqlite_version()': '3.15.0' } ]


But if I use the Promise wrapper:

$ node -e
'require("sqlite").open(":memory:").then(function(d){d.all("select
sqlite_version()").then(console.log)})'

[ { 'sqlite_version()': '3.9.1' } ]


...because it has its own version:

├─ sqlite@2.2.0

│  ├─ nan@2.3.5

│  ├─ node-pre-gyp@0.6.30

│  │  ├─ mkdirp@~0.5.0

│  │  ├─ nopt@~3.0.1

│  │  ├─ npmlog@4.x

│  │  ├─ rc@~1.1.0

│  │  ├─ request@2.x

│  │  ├─ rimraf@~2.5.0

│  │  ├─ semver@~5.3.0

│  │  ├─ tar-pack@~3.1.0

│  │  └─ tar@~2.2.0

│  ├─ once@1.3.3

│  │  └─ wrappy@1

│  ├─ sqlite3@^3.1.4

│  ├─ sqlite3@3.1.6

│  │  ├─ nan@~2.3.3

│  │  └─ node-pre-gyp@~0.6.28

│  ├─ tar-pack@3.1.4

│  │  ├─ debug@~2.2.0

│  │  ├─ fstream-ignore@~1.0.5

│  │  ├─ fstream@~1.0.10

│  │  ├─ once@~1.3.3

│  │  ├─ readable-stream@~2.1.4

│  │  ├─ rimraf@~2.5.1

│  │  ├─ tar@~2.2.1

│  │  └─ uid-number@~0.0.6

│  └─ uid-number@0.0.6

├─ sqlite3@3.1.7

│  ├─ nan@~2.4.0

│  └─ node-pre-gyp@~0.6.31

Is that what is happening for you?

**Comment by osi-oswald** [comment]
OK, I get `3.15.0` as well through `sqlite3`, thx!

**Pull request merged**
