### PR TITLE
Node v10 support (WIP)

### PR DESCRIPTION
**Pull request by kewde**
#973

### CODE REVIEW

**Comment by springmeyer** [comment]
Looking great so far. Thank you for working on this. I think you will need a nan update too.

**Comment by springmeyer** [comment]
And pulling in latest node-pre-gyp release

**Comment by kewde** [comment]
@springmeyer 
nan does not yet support v10 (as far as I can see on their github).
node-pre-gyp's version was updated in the package.json

**Comment by kewde** [comment]
Linux & OSX build fine.

Windows build errors:
```
c:\users\appveyor\.node-gyp\10.0.0\include\node\v8.h(2511): error C2144: syntax error : 'int' should be preceded by ';' (..\src\database.cc) [C:\projects\node-sqlite3\build\node_sqlite3.vcxproj]
c:\users\appveyor\.node-gyp\10.0.0\include\node\v8.h(2511): error C2144: syntax error : 'int' should be preceded by ';' (..\src\node_sqlite3.cc) [C:\projects\node-sqlite3\build\node_sqlite3.vcxproj]
c:\users\appveyor\.node-gyp\10.0.0\include\node\v8.h(2511): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int (..\src\database.cc) [C:\projects\node-sqlite3\build\node_sqlite3.vcxproj]
c:\users\appveyor\.node-gyp\10.0.0\include\node\v8.h(2511): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int (..\src\node_sqlite3.cc) [C:\projects\node-sqlite3\build\node_sqlite3.vcxproj]
c:\users\appveyor\.node-gyp\10.0.0\include\node\v8.h(4119): error C2610: 'v8::WasmCompiledModule::TransferrableModule::TransferrableModule(v8::WasmCompiledModule::TransferrableModule &&)' : is not a special member function which can be defaulted (..\src\database.cc) [C:\projects\node-sqlite3\build\node_sqlite3.vcxproj]
c:\users\appveyor\.node-gyp\10.0.0\include\node\v8.h(4119): error C2610: 'v8::WasmCompiledModule::TransferrableModule::TransferrableModule(v8::WasmCompiledModule::TransferrableModule &&)' : is not a special member function which can be defaulted (..\src\node_sqlite3.cc) [C:\projects\node-sqlite3\build\node_sqlite3.vcxproj]
c:\users\appveyor\.node-gyp\10.0.0\include\node\v8.h(4122): error C2610: 'v8::WasmCompiledModule::TransferrableModule &v8::WasmCompiledModule::TransferrableModule::operator =(v8::WasmCompiledModule::TransferrableModule &&)' : is not a special member function which can be defaulted (..\src\database.cc) [C:\projects\node-sqlite3\build\node_sqlite3.vcxproj]
c:\users\appveyor\.node-gyp\10.0.0\include\node\v8.h(4122): error C2610: 'v8::WasmCompiledModule::TransferrableModule &v8::WasmCompiledModule::TransferrableModule::operator =(v8::WasmCompiledModule::TransferrableModule &&)' : is not a special member function which can be defaulted (..\src\node_sqlite3.cc) [C:\projects\node-sqlite3\build\node_sqlite3.vcxproj]
c:\users\appveyor\.node-gyp\10.0.0\include\node\v8.h(4210): error C2610: 'v8::WasmModuleObjectBuilderStreaming::WasmModuleObjectBuilderStreaming(v8::WasmModuleObjectBuilderStreaming &&)' : is not a special member function which can be defaulted (..\src\database.cc) [C:\projects\node-sqlite3\build\node_sqlite3.vcxproj]
c:\users\appveyor\.node-gyp\10.0.0\include\node\v8.h(4215): error C2610: 'v8::WasmModuleObjectBuilderStreaming &v8::WasmModuleObjectBuilderStreaming::operator =(v8::WasmModuleObjectBuilderStreaming &&)' : is not a special member function which can be defaulted (..\src\database.cc) [C:\projects\node-sqlite3\build\node_sqlite3.vcxproj]
c:\users\appveyor\.node-gyp\10.0.0\include\node\v8.h(4210): error C2610: 'v8::WasmModuleObjectBuilderStreaming::WasmModuleObjectBuilderStreaming(v8::WasmModuleObjectBuilderStreaming &&)' : is not a special member function which can be defaulted (..\src\node_sqlite3.cc) [C:\projects\node-sqlite3\build\node_sqlite3.vcxproj]
c:\users\appveyor\.node-gyp\10.0.0\include\node\v8.h(4215): error C2610: 'v8::WasmModuleObjectBuilderStreaming &v8::WasmModuleObjectBuilderStreaming::operator =(v8::WasmModuleObjectBuilderStreaming &&)' : is not a special member function which can be defaulted (..\src\node_sqlite3.cc) [C:\projects\node-sqlite3\build\node_sqlite3.vcxproj]
c:\users\appveyor\.node-gyp\10.0.0\include\node\v8.h(4477): error C2146: syntax error : missing ';' before identifier 'size_t' (..\src\database.cc) [C:\projects\node-sqlite3\build\node_sqlite3.vcxproj]
c:\users\appveyor\.node-gyp\10.0.0\include\node\v8.h(4477): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int (..\src\database.cc) [C:\projects\node-sqlite3\build\node_sqlite3.vcxproj]
c:\users\appveyor\.node-gyp\10.0.0\include\node\v8.h(4477): error C2146: syntax error : missing ';' before identifier 'size_t' (..\src\node_sqlite3.cc) [C:\projects\node-sqlite3\build\node_sqlite3.vcxproj]
c:\users\appveyor\.node-gyp\10.0.0\include\node\v8.h(4477): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int (..\src\node_sqlite3.cc) [C:\projects\node-sqlite3\build\node_sqlite3.vcxproj]
C:\Users\appveyor\.node-gyp\10.0.0\include\node\node_buffer.h(34): error C2597: illegal reference to non-static member 'v8::TypedArray::kMaxLength' (..\src\node_sqlite3.cc) [C:\projects\node-sqlite3\build\node_sqlite3.vcxproj]
C:\Users\appveyor\.node-gyp\10.0.0\include\node\node_buffer.h(34): error C2440: 'initializing' : cannot convert from 'unknown' to 'const unsigned int' (..\src\node_sqlite3.cc) [C:\projects\node-sqlite3\build\node_sqlite3.vcxproj]
          There is no context in which this conversion is possible
C:\Users\appveyor\.node-gyp\10.0.0\include\node\node_buffer.h(34): error C2597: illegal reference to non-static member 'v8::TypedArray::kMaxLength' (..\src\database.cc) [C:\projects\node-sqlite3\build\node_sqlite3.vcxproj]
C:\Users\appveyor\.node-gyp\10.0.0\include\node\node_buffer.h(34): error C2440: 'initializing' : cannot convert from 'unknown' to 'const unsigned int' (..\src\database.cc) [C:\projects\node-sqlite3\build\node_sqlite3.vcxproj]
          There is no context in which this conversion is possible
  statement.cc
  win_delay_load_hook.cc
c:\users\appveyor\.node-gyp\10.0.0\include\node\v8.h(2511): error C2144: syntax error : 'int' should be preceded by ';' (..\src\statement.cc) [C:\projects\node-sqlite3\build\node_sqlite3.vcxproj]
c:\users\appveyor\.node-gyp\10.0.0\include\node\v8.h(2511): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int (..\src\statement.cc) [C:\projects\node-sqlite3\build\node_sqlite3.vcxproj]
c:\users\appveyor\.node-gyp\10.0.0\include\node\v8.h(4119): error C2610: 'v8::WasmCompiledModule::TransferrableModule::TransferrableModule(v8::WasmCompiledModule::TransferrableModule &&)' : is not a special member function which can be defaulted (..\src\statement.cc) [C:\projects\node-sqlite3\build\node_sqlite3.vcxproj]
c:\users\appveyor\.node-gyp\10.0.0\include\node\v8.h(4122): error C2610: 'v8::WasmCompiledModule::TransferrableModule &v8::WasmCompiledModule::TransferrableModule::operator =(v8::WasmCompiledModule::TransferrableModule &&)' : is not a special member function which can be defaulted (..\src\statement.cc) [C:\projects\node-sqlite3\build\node_sqlite3.vcxproj]
c:\users\appveyor\.node-gyp\10.0.0\include\node\v8.h(4210): error C2610: 'v8::WasmModuleObjectBuilderStreaming::WasmModuleObjectBuilderStreaming(v8::WasmModuleObjectBuilderStreaming &&)' : is not a special member function which can be defaulted (..\src\statement.cc) [C:\projects\node-sqlite3\build\node_sqlite3.vcxproj]
c:\users\appveyor\.node-gyp\10.0.0\include\node\v8.h(4215): error C2610: 'v8::WasmModuleObjectBuilderStreaming &v8::WasmModuleObjectBuilderStreaming::operator =(v8::WasmModuleObjectBuilderStreaming &&)' : is not a special member function which can be defaulted (..\src\statement.cc) [C:\projects\node-sqlite3\build\node_sqlite3.vcxproj]
c:\users\appveyor\.node-gyp\10.0.0\include\node\v8.h(4477): error C2146: syntax error : missing ';' before identifier 'size_t' (..\src\statement.cc) [C:\projects\node-sqlite3\build\node_sqlite3.vcxproj]
c:\users\appveyor\.node-gyp\10.0.0\include\node\v8.h(4477): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int (..\src\statement.cc) [C:\projects\node-sqlite3\build\node_sqlite3.vcxproj]
C:\Users\appveyor\.node-gyp\10.0.0\include\node\node_buffer.h(34): error C2597: illegal reference to non-static member 'v8::TypedArray::kMaxLength' (..\src\statement.cc) [C:\projects\node-sqlite3\build\node_sqlite3.vcxproj]
C:\Users\appveyor\.node-gyp\10.0.0\include\node\node_buffer.h(34): error C2440: 'initializing' : cannot convert from 'unknown' to 'const unsigned int' (..\src\statement.cc) [C:\projects\node-sqlite3\build\node_sqlite3.vcxproj]
          There is no context in which this conversion is possible
..\src\statement.cc(277): warning C4244: 'argument' : conversion from 'int64_t' to 'int', possible loss of data [C:\projects\node-sqlite3\build\node_sqlite3.vcxproj]
gyp ERR! build error 
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:225:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=C:\\projects\\node-sqlite3\\lib\\binding\\node-v64-win32-x64\\node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=C:\\projects\\node-sqlite3\\lib\\binding\\node-v64-win32-x64" "--napi_version=3" "--node_abi_napi=napi"
gyp ERR! cwd C:\projects\node-sqlite3
gyp ERR! node -v v10.0.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=C:\projects\node-sqlite3\lib\binding\node-v64-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=C:\projects\node-sqlite3\lib\binding\node-v64-win32-x64 --napi_version=3 --node_abi_napi=napi' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\projects\node-sqlite3\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:947:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:236:5)
node-pre-gyp ERR! System Windows_NT 6.3.9600
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\projects\\node-sqlite3\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\projects\node-sqlite3
node-pre-gyp ERR! node -v v10.0.0
node-pre-gyp ERR! node-pre-gyp -v v0.10.0
node-pre-gyp ERR! not ok 
Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=C:\projects\node-sqlite3\lib\binding\node-v64-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=C:\projects\node-sqlite3\lib\binding\node-v64-win32-x64 --napi_version=3 --node_abi_napi=napi' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sqlite3@4.0.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sqlite3@4.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by Apollon77** [comment]
experienced that windows error with node10 too

**Comment by kewde** [comment]
```
c:\users\appveyor\.node-gyp\10.1.0\include\node\v8.h(2511): error C2144: syntax error : 'int' should be preceded by ';' (..\src\database.cc) [C:\projects\node-sqlite3\build\node_sqlite3.vcxproj]
c:\users\appveyor\.node-gyp\10.1.0\include\node\v8.h(2511): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int (..\src\database.cc) [C:\projects\node-sqlite3\build\node_sqlite3.vcxproj]
c:\users\appveyor\.node-gyp\10.1.0\include\node\v8.h(2511): error C2144: syntax error : 'int' should be preceded by ';' (..\src\node_sqlite3.cc) [C:\projects\node-sqlite3\build\node_sqlite3.vcxproj]
c:\users\appveyor\.node-gyp\10.1.0\include\node\v8.h(2511): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int (..\src\node_sqlite3.cc) [C:\projects\node-sqlite3\build\node_sqlite3.vcxproj]
c:\users\appveyor\.node-gyp\10.1.0\include\node\v8.h(4119): error C2610: 'v8::WasmCompiledModule::TransferrableModule::TransferrableModule(v8::WasmCompiledModule::TransferrableModule &&)' : is not a special member function which can be defaulted (..\src\database.cc) [C:\projects\node-sqlite3\build\node_sqlite3.vcxproj]
c:\users\appveyor\.node-gyp\10.1.0\include\node\v8.h(4122): error C2610: 'v8::WasmCompiledModule::TransferrableModule &v8::WasmCompiledModule::TransferrableModule::operator =(v8::WasmCompiledModule::TransferrableModule &&)' : is not a special member function which can be defaulted (..\src\database.cc) [C:\projects\node-sqlite3\build\node_sqlite3.vcxproj]
c:\users\appveyor\.node-gyp\10.1.0\include\node\v8.h(4119): error C2610: 'v8::WasmCompiledModule::TransferrableModule::TransferrableModule(v8::WasmCompiledModule::TransferrableModule &&)' : is not a special member function which can be defaulted (..\src\node_sqlite3.cc) [C:\projects\node-sqlite3\build\node_sqlite3.vcxproj]
c:\users\appveyor\.node-gyp\10.1.0\include\node\v8.h(4122): error C2610: 'v8::WasmCompiledModule::TransferrableModule &v8::WasmCompiledModule::TransferrableModule::operator =(v8::WasmCompiledModule::TransferrableModule &&)' : is not a special member function which can be defaulted (..\src\node_sqlite3.cc) [C:\projects\node-sqlite3\build\node_sqlite3.vcxproj]
c:\users\appveyor\.node-gyp\10.1.0\include\node\v8.h(4210): error C2610: 'v8::WasmModuleObjectBuilderStreaming::WasmModuleObjectBuilderStreaming(v8::WasmModuleObjectBuilderStreaming &&)' : is not a special member function which can be defaulted (..\src\database.cc) [C:\projects\node-sqlite3\build\node_sqlite3.vcxproj]
c:\users\appveyor\.node-gyp\10.1.0\include\node\v8.h(4215): error C2610: 'v8::WasmModuleObjectBuilderStreaming &v8::WasmModuleObjectBuilderStreaming::operator =(v8::WasmModuleObjectBuilderStreaming &&)' : is not a special member function which can be defaulted (..\src\database.cc) [C:\projects\node-sqlite3\build\node_sqlite3.vcxproj]
c:\users\appveyor\.node-gyp\10.1.0\include\node\v8.h(4210): error C2610: 'v8::WasmModuleObjectBuilderStreaming::WasmModuleObjectBuilderStreaming(v8::WasmModuleObjectBuilderStreaming &&)' : is not a special member function which can be defaulted (..\src\node_sqlite3.cc) [C:\projects\node-sqlite3\build\node_sqlite3.vcxproj]
c:\users\appveyor\.node-gyp\10.1.0\include\node\v8.h(4215): error C2610: 'v8::WasmModuleObjectBuilderStreaming &v8::WasmModuleObjectBuilderStreaming::operator =(v8::WasmModuleObjectBuilderStreaming &&)' : is not a special member function which can be defaulted (..\src\node_sqlite3.cc) [C:\projects\node-sqlite3\build\node_sqlite3.vcxproj]
c:\users\appveyor\.node-gyp\10.1.0\include\node\v8.h(4477): error C2146: syntax error : missing ';' before identifier 'size_t' (..\src\database.cc) [C:\projects\node-sqlite3\build\node_sqlite3.vcxproj]
c:\users\appveyor\.node-gyp\10.1.0\include\node\v8.h(4477): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int (..\src\database.cc) [C:\projects\node-sqlite3\build\node_sqlite3.vcxproj]
c:\users\appveyor\.node-gyp\10.1.0\include\node\v8.h(4477): error C2146: syntax error : missing ';' before identifier 'size_t' (..\src\node_sqlite3.cc) [C:\projects\node-sqlite3\build\node_sqlite3.vcxproj]
c:\users\appveyor\.node-gyp\10.1.0\include\node\v8.h(4477): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int (..\src\node_sqlite3.cc) [C:\projects\node-sqlite3\build\node_sqlite3.vcxproj]
C:\Users\appveyor\.node-gyp\10.1.0\include\node\node_buffer.h(34): error C2597: illegal reference to non-static member 'v8::TypedArray::kMaxLength' (..\src\database.cc) [C:\projects\node-sqlite3\build\node_sqlite3.vcxproj]
C:\Users\appveyor\.node-gyp\10.1.0\include\node\node_buffer.h(34): error C2440: 'initializing' : cannot convert from 'unknown' to 'const unsigned int' (..\src\database.cc) [C:\projects\node-sqlite3\build\node_sqlite3.vcxproj]
          There is no context in which this conversion is possible
C:\Users\appveyor\.node-gyp\10.1.0\include\node\node_buffer.h(34): error C2597: illegal reference to non-static member 'v8::TypedArray::kMaxLength' (..\src\node_sqlite3.cc) [C:\projects\node-sqlite3\build\node_sqlite3.vcxproj]
C:\Users\appveyor\.node-gyp\10.1.0\include\node\node_buffer.h(34): error C2440: 'initializing' : cannot convert from 'unknown' to 'const unsigned int' (..\src\node_sqlite3.cc) [C:\projects\node-sqlite3\build\node_sqlite3.vcxproj]
          There is no context in which this conversion is possible
  statement.cc
  win_delay_load_hook.cc
c:\users\appveyor\.node-gyp\10.1.0\include\node\v8.h(2511): error C2144: syntax error : 'int' should be preceded by ';' (..\src\statement.cc) [C:\projects\node-sqlite3\build\node_sqlite3.vcxproj]
c:\users\appveyor\.node-gyp\10.1.0\include\node\v8.h(2511): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int (..\src\statement.cc) [C:\projects\node-sqlite3\build\node_sqlite3.vcxproj]
c:\users\appveyor\.node-gyp\10.1.0\include\node\v8.h(4119): error C2610: 'v8::WasmCompiledModule::TransferrableModule::TransferrableModule(v8::WasmCompiledModule::TransferrableModule &&)' : is not a special member function which can be defaulted (..\src\statement.cc) [C:\projects\node-sqlite3\build\node_sqlite3.vcxproj]
c:\users\appveyor\.node-gyp\10.1.0\include\node\v8.h(4122): error C2610: 'v8::WasmCompiledModule::TransferrableModule &v8::WasmCompiledModule::TransferrableModule::operator =(v8::WasmCompiledModule::TransferrableModule &&)' : is not a special member function which can be defaulted (..\src\statement.cc) [C:\projects\node-sqlite3\build\node_sqlite3.vcxproj]
c:\users\appveyor\.node-gyp\10.1.0\include\node\v8.h(4210): error C2610: 'v8::WasmModuleObjectBuilderStreaming::WasmModuleObjectBuilderStreaming(v8::WasmModuleObjectBuilderStreaming &&)' : is not a special member function which can be defaulted (..\src\statement.cc) [C:\projects\node-sqlite3\build\node_sqlite3.vcxproj]
c:\users\appveyor\.node-gyp\10.1.0\include\node\v8.h(4215): error C2610: 'v8::WasmModuleObjectBuilderStreaming &v8::WasmModuleObjectBuilderStreaming::operator =(v8::WasmModuleObjectBuilderStreaming &&)' : is not a special member function which can be defaulted (..\src\statement.cc) [C:\projects\node-sqlite3\build\node_sqlite3.vcxproj]
c:\users\appveyor\.node-gyp\10.1.0\include\node\v8.h(4477): error C2146: syntax error : missing ';' before identifier 'size_t' (..\src\statement.cc) [C:\projects\node-sqlite3\build\node_sqlite3.vcxproj]
c:\users\appveyor\.node-gyp\10.1.0\include\node\v8.h(4477): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int (..\src\statement.cc) [C:\projects\node-sqlite3\build\node_sqlite3.vcxproj]
C:\Users\appveyor\.node-gyp\10.1.0\include\node\node_buffer.h(34): error C2597: illegal reference to non-static member 'v8::TypedArray::kMaxLength' (..\src\statement.cc) [C:\projects\node-sqlite3\build\node_sqlite3.vcxproj]
C:\Users\appveyor\.node-gyp\10.1.0\include\node\node_buffer.h(34): error C2440: 'initializing' : cannot convert from 'unknown' to 'const unsigned int' (..\src\statement.cc) [C:\projects\node-sqlite3\build\node_sqlite3.vcxproj]
          There is no context in which this conversion is possible
..\src\statement.cc(277): warning C4244: 'argument' : conversion from 'int64_t' to 'int', possible loss of data [C:\projects\node-sqlite3\build\node_sqlite3.vcxproj]
```

**Comment by springmeyer** [comment]
Took a look at the windows errors for node v10. I think they are the same as https://github.com/mapbox/node-sqlite3/issues/920 - we need `msvs_toolset: 14`. I'll merge now and fix in master. Thank you again for starting this @kewde

**Comment by Apollon77** [comment]
Verified.

**Pull request merged**
