### PR TITLE
User functions

### LINKED ISSUE #140: User Defined Functions?
I'm looking for a way to create user functions. In PHP's binding to SQLite3 there is a way to [create functions at runtime](http://php.net/manual/en/sqlite3.createfunction.php). I'm thinking that if there were something similar in node-sqlite3 it would be awesome.

I don't want to try loading an extension because that would require me to keep tabs on versions and / or incorporating a compilation step in my modules. I'd rather just define functions in the javascript and be able to hook them into SQLite for use in queries.

http://www.sqlite.org/lang_expr.html#regexp
http://www.sqlite.org/c3ref/create_function.html

### PR DESCRIPTION
**Pull request by rlindner81**
Based on PR https://github.com/mapbox/node-sqlite3/pull/448 by @wbyoung
This also fixes #140 

* I updated the syntax to work with the current `nan`
* I also added a cleanup mechanism very loosely inspired by https://github.com/python/cpython/blob/master/Modules/_sqlite/connection.c#L848

Without the cleanup, the `async_t` handlers used here will always be considered active by libuv making node run forever. I suspect that is also what @springmeyer observed on the travis builds.

NOTE: I have very little experience programming in node C/C++ addons, so a thorough review would be appreciated.

### CODE REVIEW

**Comment by kewde** [comment]
Thank you for your contribution @rlindner81, I will take a look at this.

**Comment by rlindner81** [comment]
@kewde If you need any input to expedite the process, I can do some more work on this.

**Comment by SamuelBrucksch** [comment]
@kewde, is there any progress on this? I would really appreciate this functionality.

**Comment by RobinMalfait** [comment]
Is there anything I can help with to get this functionality merged?

**Comment by rlindner81** [comment]
@RobinMalfait I don't think this will be merged. I never heard back from @kewde

**Comment by RobinMalfait** [comment]
Thanks for your work though @rlindner81 !

**Comment by RobinMalfait** [comment]
@rlindner81 I am currently your branch for our tests, however in our case Jest keeps on running without never cleanly exiting. 

image

I wonder if you might know why this happens and eventually how to fix this. I am no C++ programmer, but if you happen to know _where_ to start looking (the --detectOpenHandles also never finishes 🙃 ) that would be highly appreciated!

Thanks in advance!

**Comment by rlindner81** [comment]
Hi @RobinMalfait, these types of bugs are hard to track down in my experience. Start by double-checking that the problem is caused by the changes in this branch. Then I would track it down further by commenting large amounts of code and seeing if that fixes it... You have to do a kind of binary search for the culprit that way. 
The code in this branch is unfortunately hopelessly outdated and I will not invest more work in it sorry. I close the PR to make that clearer.

**Comment by SamuelBrucksch** [comment]
Too bad, thanks for your work Richard. Guess we have to look for something else then.

**Pull request closed without merging**
