### PR TITLE
Nan2

### LINKED ISSUE #487: build is broken on io.js 3
The build is broken on the newest io.js (3) version, updating NAN also doesn't help it.

```
In file included from ../src/database.cc:5:0:
../src/database.h: In statischer Elementfunktion »static bool node_sqlite3::Database::HasInstance(v8::Handle<v8::Value>)«:
../src/database.h:28:18: Fehler: »NanScope« wurde in diesem Gültigkeitsbereich nicht definiert
         NanScope();
                  ^
../src/database.h:31:43: Fehler: »NanNew« wurde in diesem Gültigkeitsbereich nicht definiert
         return NanNew(constructor_template)->HasInstance(obj);
                                           ^
../src/database.h: In Konstruktor »node_sqlite3::Database::Baton::Baton(node_sqlite3::Database*, v8::Handle<v8::Function>)«:
../src/database.h:45:46: Fehler: »NanAssignPersistent« wurde in diesem Gültigkeitsbereich nicht definiert
             NanAssignPersistent(callback, cb_);
                                              ^
../src/database.h: In Destruktor »virtual node_sqlite3::Database::Baton::~Baton()«:
../src/database.h:49:42: Fehler: »NanDisposePersistent« wurde in diesem Gültigkeitsbereich nicht definiert
             NanDisposePersistent(callback);
                                          ^
In file included from ../src/database.cc:6:0:
../src/statement.h: Im globalen Gültigkeitsbereich:
../src/statement.h:224:32: Fehler: »_NAN_METHOD_ARGS« wurde in diesem Gültigkeitsbereich nicht definiert
     template <class T> T* Bind(_NAN_METHOD_ARGS, int start = 0, int end = -1);
                                ^
../src/statement.h:224:50: Fehler: expected primary-expression before »int«
     template <class T> T* Bind(_NAN_METHOD_ARGS, int start = 0, int end = -1);
                                                  ^
../src/statement.h:224:65: Fehler: expected primary-expression before »int«
     template <class T> T* Bind(_NAN_METHOD_ARGS, int start = 0, int end = -1);
                                                                 ^
../src/statement.h:224:78: Fehler: Datenelement »Bind« kann kein Elementtemplate sein
     template <class T> T* Bind(_NAN_METHOD_ARGS, int start = 0, int end = -1);
                                                                              ^
../src/statement.h: In Konstruktor »node_sqlite3::Statement::Baton::Baton(node_sqlite3::Statement*, v8::Handle<v8::Function>)«:
../src/statement.h:91:46: Fehler: »NanAssignPersistent« wurde in diesem Gültigkeitsbereich nicht definiert
             NanAssignPersistent(callback, cb_);
                                              ^
../src/statement.h: In Destruktor »virtual node_sqlite3::Statement::Baton::~Baton()«:
../src/statement.h:99:42: Fehler: »NanDisposePersistent« wurde in diesem Gültigkeitsbereich nicht definiert
             NanDisposePersistent(callback);
                                          ^
../src/statement.h: In Destruktor »virtual node_sqlite3::Statement::EachBaton::~EachBaton()«:
../src/statement.h:131:43: Fehler: »NanDisposePersistent« wurde in diesem Gültigkeitsbereich nicht definiert
             NanDisposePersistent(completed);
                                           ^
../src/statement.h: In Destruktor »node_sqlite3::Statement::Async::~Async()«:
../src/statement.h:183:41: Fehler: »NanDisposePersistent« wurde in diesem Gültigkeitsbereich nicht definiert
             NanDisposePersistent(item_cb);
                                         ^
../src/database.cc: In statischer Elementfunktion »static void node_sqlite3::Database::Init(v8::Handle<v8::Object>)«:
../src/database.cc:13:14: Fehler: »NanScope« wurde in diesem Gültigkeitsbereich nicht definiert
     NanScope();
              ^
../src/database.cc:15:33: Fehler: »NanNew« wurde in diesem Gültigkeitsbereich nicht definiert
     Local<FunctionTemplate> t = NanNew<FunctionTemplate>(New);
                                 ^
../src/database.cc:15:56: Fehler: expected primary-expression before »>« token
     Local<FunctionTemplate> t = NanNew<FunctionTemplate>(New);
                                                        ^
../src/database.cc:20:48: Fehler: ungültige Umwandlung von »Nan::NAN_METHOD_RETURN_TYPE (*)(Nan::NAN_METHOD_ARGS_TYPE) {aka void (*)(const Nan::FunctionCallbackInfo<v8::Value>&)}« in »v8::FunctionCallback {aka void (*)(const v8::FunctionCallbackInfo<v8::Value>&)}« [-fpermissive]
     NODE_SET_PROTOTYPE_METHOD(t, "close", Close);
                                                ^
```

### PR DESCRIPTION
**Pull request by kkoopa**
Fixes #487.

### CODE REVIEW

**Comment by rmg** [comment]
The only "interesting" part of this PR is the change to the unicode test. Everything else looks like a straightforward port.

Would be nice to see this merged.

**Comment by rmg** [comment]
t might be handy to update appveyor.yml as part of this PR to include iojs-v3, assuming appveyor supports it.

**Comment by rmg** [comment]
The build error looks like appveyor may not have 3.1.0 yet :-(

**Comment by sam-github** [comment]
@mapbox Any chance of getting this released? v3.x is beta for upcoming v4.x "converged release", this is important

**Comment by springmeyer** [comment]
Thank you for this huge contribution @kkoopa - will merge now. Apologies for the delay. Please get in touch if any of you would like to help co-maintain this module to help prevent future delays.

**Comment by imZack** [comment]
still waiting for `npm publish`, please. :sparkles:

**Comment by zack9433** [comment]
+1

**Comment by lancetw** [comment]
+1

**Comment by fengmk2** [comment]
+1 for publish new version to npm.

**Comment by horsekitlin** [comment]
+1

**Comment by cwonrails** [comment]
+1

**Comment by springmeyer** [comment]
v3.1.0 is now out that includes this fix (https://github.com/mapbox/node-sqlite3/blob/master/CHANGELOG.md#310)

**Comment by fengmk2** [comment]
@springmeyer great!

**Pull request merged**
