### PR TITLE
electron osx builds

### PR DESCRIPTION
**Pull request by kewde**

### CODE REVIEW

**Comment by kewde** [comment]
Bins are building fine, the test suite isn't running because the Travis-CI environment is headless.
I'm hoping to resolve it.

**Comment by kewde** [comment]
@springmeyer 

There are no OSX builds being uploaded. Can you please publish a build and give me a ping?
I'll verify that they are being uploaded correctly.

**Comment by kewde** [comment]
Please restart the following job, test all pass, seems like an issue with homebrew:
https://travis-ci.org/mapbox/node-sqlite3/jobs/430224908

**Comment by nocodaio** [comment]
@springmeyer Would it be possible to get this change into master so it publishes the binaries correctly to S3? 

Thanks again for the quick fix @kewde

**Comment by springmeyer** [comment]
@kewde I'm unable to do this work since I've switched roles at Mapbox. However I've added you as a contributor if you can merge and run out the release yourself. /cc @mapsam

**Comment by kewde** [comment]
I've accepted the invitation, I'll wait for @mapsam for further input.
Is there a point of contact if I run into obstacles?

**Comment by mapsam** [comment]
@kewde @springmeyer thanks for the ping - this looks good to me 👍 taking a look at the failing job right now

**Comment by mapsam** [comment]
Ah, looks like this failure isn't related and is happening in other branches. @kewde feel free to merge and publish binaries for electron/osx. Do you think it would suffice to republish on the current version 4.0.2? Otherwise I'd be happy with a 4.1.0 release if that makes sense to you.

**Comment by kewde** [comment]
It would suffice I suppose. What the release procedure? Is it just as simple as adding the publish command in the latest commit? @mapsam @springmeyer

**Comment by mapsam** [comment]
Release procedure is documented in the CONTRIBUTING.md here https://github.com/mapbox/node-sqlite3/blob/master/CONTRIBUTING.md#releasing

Not sure if you've been added to the NPM org - if not I can hit that final button when ready, just let me know. Once this branch is merged, you can make the release commit directly on master with the `[publish binary]` string added to the end of the commit message. Here's an example release commit from @springmeyer https://github.com/mapbox/node-sqlite3/commit/93c9ecc25c8d3de63eef7a59b9b9b7e8da6359af

@springmeyer any quick ideas on why https://travis-ci.org/mapbox/node-sqlite3/jobs/430224893 is failing?

**Comment by kewde** [comment]
@mapsam @springmeyer 

Could someone make a npm package release for 4.0.3, I've merged all electron changes.
Alternatively, add me as a collaborator there.

**Comment by mapsam** [comment]
@kewde just got set up on npm myself for sqlite3 - 4.0.3 has been published! Thanks so much.

**Comment by nocodaio** [comment]
Just downloaded the pre-built OSX package for Electron! Appreciate all the effort folks 👍

**Comment by kewde** [comment]
@nocodaio please let me know if there are any issues, thanks!

**Pull request merged**
