### PR TITLE
Build for Node.js 12

### LINKED ISSUE #1138: Release new version
The current sqlite3 version does not work together with Node.js v12.0.0-pre. This is already fixed on master but there's no new version released so far. I would like to point out that the official release date for Node.js v12 is very soon and it would be great to have a clean [CITGM](https://github.com/nodejs/citgm) result on Node.js side.

Is there a plan to release a new version anytime soon?

### PR DESCRIPTION
**Pull request by oncletom**
fixes #1138

### CODE REVIEW

**Comment by oncletom** [comment]
But apparently there is still a requirement to deploy the binaries manually, somewhere.

**Comment by kewde** [comment]
Triggered the CI again.

**Comment by kewde** [comment]
depends on #11454

**Comment by kewde** [comment]
Node 12 is still not supported on AppVeyor.
```
downloading/installing node
node  x86 package not found
At C:\Program Files\AppVeyor\BuildAgent\Modules\avvm\avvm.psm1:106 char:17
+                 throw "$product $version $platform package not found"
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (node  x86 package not found:S 
   tring) [], RuntimeException
    + FullyQualifiedErrorId : node  x86 package not found
 
~~~~~~~~~~~~~~~~~~~~~~ ERROR C:\projects\node-sqlite3\scripts\build-appveyor.bat ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by kewde** [comment]
Using Node 12 will automatically upgrade the Travis VM to Xenial, will also need the new XVFB service.

**Comment by kewde** [comment]
Closing in favor of #1158 & #1160

**Pull request closed without merging**
