### PR TITLE
Add NodeJS 11

### PR DESCRIPTION
**Pull request by kewde**

### CODE REVIEW

**Comment by kibertoad** [comment]
Maybe appveyor CI could be extracted into a separate PR to unblock the fix?

**Comment by kibertoad** [comment]
@kewde Could you rerun tests? I think appveyor got Node 11 already.

**Comment by panther7** [comment]
Any news?

**Comment by panther7** [comment]
I hate this ignoring, maintener?

**Comment by kewde** [comment]
@kibertoad rerunning.

**Comment by kibertoad** [comment]
@kewde Node 11 passed, some other random failures happened. Probably needs to be triggered again (btw, you don't need comment for that, closing and reopening the PR does the trick)

**Comment by kewde** [comment]
@kibertoad I've merged the NodeJS 11 code and started the binary publishing process.
It will take a few hours before these are available.

**Comment by kewde** [comment]
Still waiting for version 4.0.4 to be published to npm though. See #1077

**Comment by panther7** [comment]
Thanks

**Comment by springmeyer** [comment]
> Still waiting for version 4.0.4 to be published to npm though. See #1077
This is now done

**Pull request merged**
