### PR TITLE
update sqlite3 version to 3320200

### PR DESCRIPTION
**Pull request by aberezovski**
Update the sqlite3 to point to the latest sqlite distribution https://www.sqlite.org/releaselog/3_32_2.html.

The link to the sqlite source code from the original web site https://www.sqlite.org/2020/sqlite-autoconf-3320200.tar.gz

### CODE REVIEW

**Comment by aberezovski** [comment]
I see the `ci/aooveyor/pr` check fails due the job https://ci.appveyor.com/project/Mapbox/node-sqlite3/builds/33337967/job/ar6acf2ffqr67nir.
What can I do to overcome that failure?

**Comment by aberezovski** [comment]
Changed the sqlite distribution version to [3.32.1](https://www.sqlite.org/releaselog/3_32_1.html) that is considered stable version and is available in official aliline 3.12 repo.

**Comment by kewde** [comment]
Hi,
I will be releasing this ASAP (5.0.1).

**Comment by aberezovski** [comment]
Hi @kewde,
Thanks for your approval and intention to create a new release 5.0.1
I saw a new release for SQLite 3.32.3 https://www.sqlite.org/releaselog/3_32_3.html
Is the any chance to update the current PR to point to the latest SQLite release?

**Comment by aberezovski** [comment]
Let me know if I have time to make the change.

**Comment by aberezovski** [comment]
One more [PR](https://github.com/mapbox/node-sqlite3/pull/1353) that points to the latest sqlite distribution [3.32.3](https://www.sqlite.org/releaselog/3_32_3.html)

**Comment by kewde** [comment]
#1351

**Pull request closed without merging**
