### PR TITLE
Sqlite 3.26.0.

### PR DESCRIPTION
**Pull request by bruce-one**
Replaces #1087 as 3.26.0 came out.

### CODE REVIEW

**Comment by kewde** [comment]
SHA1 hash of the file provided by bruce-one.
```
user@host:~/Downloads$ sha1sum sqlite-autoconf-3260000.tar.gz 
9af2df1a6da5db6e2ecf3f463625f16740e036e9  sqlite-autoconf-3260000.tar.gz
```

https://sqlite.org/download.html
```
sqlite-autoconf-3260000.tar.gz(2.65 MiB)
(sha1: 9af2df1a6da5db6e2ecf3f463625f16740e036e9)
```

Looks clean :+1:

**Comment by bruce-one** [comment]
Thanks for the merge! :-)

**Comment by kewde** [comment]
SHA256 to be sure :+1: 

commit 924cf56 
```
sha256sum sqlite-autoconf-3260000.tar.gz 
5daa6a3fb7d1e8c767cd59c4ded8da6e4b00c61d3b466d0685e35c4dd6d7bf5d  sqlite-autoconf-3260000.tar.gz
```

Downloaded from https://sqlite.org/download.html
```
sha256sum sqlite-autoconf-3260000.tar.gz 
5daa6a3fb7d1e8c767cd59c4ded8da6e4b00c61d3b466d0685e35c4dd6d7bf5d  sqlite-autoconf-3260000.tar.gz
```

**Comment by bpasero** [comment]
@kewde you might want to publish a new version with this included given https://blade.tencent.com/magellan/index_en.html

**Comment by kewde** [comment]
@bpasero 
Thank you for the notice, I wasn't aware of that issue.

I will get a new build out ASAP.

**Comment by bpasero** [comment]
@kewde great thanks

**Pull request merged**
