### PR TITLE
sqlite3 update to 3.35.2 (3350200)

### PR DESCRIPTION
**Pull request by charlesj**
3.35 adds several nice new features, including `returning`

### CODE REVIEW

**Comment by border-radius** [comment]
Tested this brunch locally, all tests passed:
```
  161 passing (29s)
```
Can anyone trigger travis-ci to rerun tests?

**Comment by border-radius** [comment]
Hmm, forked your fork and installed in my project:
```bash
npm i border-radius/node-sqlite3 --save
```
Tried this query:
```js
db.get('INSERT INTO invites (token) VALUES (?) RETURNING *', [token], (e, row) => {
  //...
})
```
But still getting this error:
```
Error: SQLITE_ERROR: near "RETURNING": syntax error
```
:thinking:

**Comment by mscdex** [comment]
@border-radius You might want to double check that node-pre-gyp isn't installing/using a prebuilt/precompiled addon for your platform. Try adding `--build-from-source` to your npm installation command line to ensure that's not the case.

**Comment by rustyconover** [comment]
Any updates on this merge?

**Comment by johan13** [comment]
I am looking forward to getting this merged!

Since this PR was opened there has been a few bug fixes. Maybe we should try to get 3.35.5 merged instead?

**Comment by Glowin** [comment]
@johan13 Any update of sqlite3 latest version? the latest version is 3.36.0 now. https://www.sqlite.org/releaselog/3_36_0.html

**Comment by johan13** [comment]
> @johan13 Any update of sqlite3 latest version? the latest version is 3.36.0 now. https://www.sqlite.org/releaselog/3_36_0.html

No, I never got around to that. Thanks for submitting #1476. Let's hope it receives more attention from the maintainers than this PR did.

**Comment by kewde** [comment]
Thank you for your contribution, but a newer version was merged.

**Pull request closed without merging**
