### PR TITLE
update sqlite3 version to 3310100

### PR DESCRIPTION
**Pull request by anlexN**

### CODE REVIEW

**Comment by anlexN** [comment]
travis is failed. i don't know what's wrong.

**Comment by anlexN** [comment]
travis is very slow, can we move to another ci?

**Comment by kewde** [comment]
@anlexN Thank you very much for the contribution, I will verify the hashes & if they match with what's on the website then I will merge. I appreciate this a lot, good work!

**Comment by anlexN** [comment]
@kewde , how to learn mordern C++? I have done google search, but those material is very old.

**Comment by kewde** [comment]
Hi,

**SHA1 SUMS:**
File in this PR.
```
user@host:~/projects/mapbox/node-sqlite3/deps$ sha1sum sqlite-autoconf-3310100.tar.gz 
0c30f5b22152a8166aa3bebb0f4bc1f3e9cc508b  sqlite-autoconf-3310100.tar.gz
```
Matches with the website :+1: 

**SHA256 SUM:**
File in this PR.
```
user@host:~/projects/mapbox/node-sqlite3/deps$ sha256sum sqlite-autoconf-3310100.tar.gz 
62284efebc05a76f909c580ffa5c008a7d22a1287285d68b7825a2b6b51949ae  sqlite-autoconf-3310100.tar.gz
```
Matches with the file downloaded from the website :+1: 

Thank you for the contributions, other feel free to verify the checksums.

**Comment by anlexN** [comment]
where is official sqlite sha256? I only find sha1.
image
image

**Pull request merged**
