### PR TITLE
build: Support docker to build ARM package

### PR DESCRIPTION
**Pull request by rzr**
It was build on Raspbian using docker and binfmt+qemu

Usage:
    curl -sL https://rawgit.com/$org/$project/$branch/run.sh | bash -x -
    ls tmp/out/node-sqlite3/sqlite3-*.tgz

Or run.sh can be run insources

Change-Id: I79000463955d16eec8809c870f7d02c60da53432
Bug: https://github.com/mapbox/node-sqlite3/issues/418
Origin: https://github.com/tizenteam/node-sqlite3
Signed-off-by: Philippe Coval <p.coval@samsung.com>

### CODE REVIEW

**Comment by rzr** [comment]
download package from https://bintray.com/rzr/devel/

**Comment by kewde** [comment]
Hi @rzr 

First of all, thank you for your contributions. I think I can merge this as is. Is this still a WIP?
Ideally we would run this the Travis CI environment. It does not directly support ARM but it can be emulated. Ideally we publish builds for ARM too, are you interested in adding this?.

**Comment by tkurki** [comment]
@kewde see https://github.com/mapbox/node-sqlite3/issues/418#issuecomment-455282053 for a working example of Travis building ARM binary with Docker. I had missed this PR and started from Travis perspective. The approach there is a bit simpler and I assume faster, as it uses a prebuilt arm32v7/node Docker image.

**Comment by tkurki** [comment]
@rzr you force pushed something and this PR no longer does what the title and description say?

**Comment by kewde** [comment]
The interesting QEMU bits for ARM can be found in here:
https://github.com/TizenTeam/node-sqlite3/commit/e969908dd48f34e67bce795912e0005eabe7f2e7

**Comment by rzr** [comment]
See updates in:
https://github.com/mapbox/node-sqlite3/issues/418

**Comment by rzr** [comment]
Which version of ARM is proffered ? I assume raspbian's one 

Meanwhile check this ARMv8 change:

Relate-to: https://github.com/mapbox/node-sqlite3/pull/1147

I will adapt it for ARMv7 then

**Comment by rzr** [comment]
May this one be merged 1st:
https://github.com/mapbox/node-sqlite3/pull/1147

**Pull request closed without merging**
