### PR TITLE
deps: alternative update of node-gyp for electron (v5 & v6), windows

### PR DESCRIPTION
**Pull request by kewde**

### CODE REVIEW

**Comment by kewde** [comment]
node-pre-gyp seems to be falling back to node-gyp which is installed in:
```
C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js
```

Including node-gyp into the package does not help, neither does installing it globally with the -g flag.

**Comment by kewde** [comment]
The updated version however is present at 
```
C:\Users\appveyor\AppData\Roaming\npm\node-gyp -> C:\Users\appveyor\AppData\Roaming\npm\node_modules\node-gyp\bin\node-gyp.js```

**Comment by kewde** [comment]
@bruce-one It's a long shot, but I could use someone to take a look at this because it's driving me crazy. This should be a simple batch change yet I can't get it right.

**Comment by kewde** [comment]
Well, apparently it's fixed now. Will release soon!

**Comment by bruce-one** [comment]
Awesome!

Sorry I wasn't able to offer any help...

**Pull request merged**
